# Generated by Django 4.0.1 on 2022-01-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvarbek_app', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
