# Generated by Django 4.0.1 on 2022-01-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvarbek_app', '0004_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
