# Generated by Django 4.0.2 on 2022-02-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvarbek_app', '0005_categories_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc_ru',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='desc_uz',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_ru',
            field=models.CharField(
                max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_uz',
            field=models.CharField(
                max_length=50, null=True, verbose_name='Название'),
        ),
    ]
