# Generated by Django 4.0.2 on 2022-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvarbek_app', '0006_products_desc_ru_products_desc_uz_products_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_uz',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Категории'),
        ),
    ]
